/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Image;
import javax.swing.ImageIcon;
import other.ImageResizer;

/**
 *
 * @author diogo
 */
public class LevelPicker extends javax.swing.JFrame {

    /**
     * Creates new form LevelPicker
     */
    public LevelPicker() {
        initComponents();
        resizeImages();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        levelPickerLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        level1 = new javax.swing.JButton();
        level2 = new javax.swing.JButton();
        level3 = new javax.swing.JButton();
        level4 = new javax.swing.JButton();
        level5 = new javax.swing.JButton();
        level6 = new javax.swing.JButton();
        level7 = new javax.swing.JButton();
        level8 = new javax.swing.JButton();
        level9 = new javax.swing.JButton();
        level10 = new javax.swing.JButton();
        voltarBt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        levelPickerLabel.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        levelPickerLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/star.png"))); // NOI18N
        levelPickerLabel.setText(" LEVELS");

        jPanel1.setLayout(new java.awt.GridLayout(2, 5, 2, 2));

        level1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        level1.setText("1");
        level1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level1ActionPerformed(evt);
            }
        });
        jPanel1.add(level1);

        level2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        level2.setText("2");
        jPanel1.add(level2);

        level3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        level3.setText("3");
        jPanel1.add(level3);

        level4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        level4.setText("4");
        jPanel1.add(level4);

        level5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        level5.setText("5");
        jPanel1.add(level5);

        level6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        level6.setText("6");
        jPanel1.add(level6);

        level7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        level7.setText("7");
        jPanel1.add(level7);

        level8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        level8.setText("8");
        jPanel1.add(level8);

        level9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        level9.setText("9");
        jPanel1.add(level9);

        level10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        level10.setText("10");
        jPanel1.add(level10);

        voltarBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/voltar.png"))); // NOI18N
        voltarBt.setText("Voltar");
        voltarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(voltarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(levelPickerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(levelPickerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(voltarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void level1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_level1ActionPerformed

    private void voltarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_voltarBtActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    public void resizeImages(){
        ImageIcon icon1 = ImageResizer.resizeImage("/resources/voltar.png", 50, 50);
        voltarBt.setIcon(icon1);
        
        ImageIcon icon2 = ImageResizer.resizeImage("/resources/star.png", 50, 50);
        levelPickerLabel.setIcon(icon2);
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LevelPicker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LevelPicker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LevelPicker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LevelPicker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LevelPicker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton level1;
    private javax.swing.JButton level10;
    private javax.swing.JButton level2;
    private javax.swing.JButton level3;
    private javax.swing.JButton level4;
    private javax.swing.JButton level5;
    private javax.swing.JButton level6;
    private javax.swing.JButton level7;
    private javax.swing.JButton level8;
    private javax.swing.JButton level9;
    private javax.swing.JLabel levelPickerLabel;
    private javax.swing.JButton voltarBt;
    // End of variables declaration//GEN-END:variables
}
